name: Waka Readme

on:
  schedule:
    # Runs at 12am IST (IST is UTC +5:30, hence 18:30 UTC)
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          DEBUG_LOGGING: "False"
          SHOW_LOC_CHART: "False"
